 void Upgrade_Tables_V7(Database db)  async{ //
        try {

            String createTableActivityapproval = "CREATE TABLE IF NOT EXISTS ${TablesBase.TABLE_ACTIVITYAPPROVAL}(${ColumnsBase.KEY_ID} INTEGER PRIMARY KEY AUTOINCREMENT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ACTIVITYAPPROVALID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ACTIVITYAPPROVALCODE} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ACTIVITYAPPROVALTITLE} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ACTIVITYAPPROVALTYPEID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ACTIVITYID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_REQUESTDATE} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_REQUESTDETAIL} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ISSUBMITTED} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_PARENTACTIVITYAPPROVALID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_APPROVALSTATUS} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_APPROVALBYAPPUSERID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_APPROVALTIME} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_APPROVERREMARKS} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_CREATEDBY} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_CREATEDON} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_MODIFIEDBY} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_MODIFIEDON} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_DEVICEIDENTIFIER} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_REFERENCEIDENTIFIER} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_LOCATION} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ISACTIVE} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_UID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_APPUSERID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_APPUSERGROUPID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ISARCHIVED} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVAL_ISDELETED} TEXT,${ColumnsBase.KEY_ISDIRTY} TEXT,${ColumnsBase.KEY_ISACTIVE} TEXT,${ColumnsBase.KEY_ISDELETED} TEXT,${ColumnsBase.KEY_UPSYNCMESSAGE} TEXT,${ColumnsBase.KEY_DOWNSYNCMESSAGE} TEXT,${ColumnsBase.KEY_SCREATEDON} TEXT,${ColumnsBase.KEY_SMODIFIEDON} TEXT,${ColumnsBase.KEY_CREATEDBYUSER} TEXT,${ColumnsBase.KEY_MODIFIEDBYUSER} TEXT,${ColumnsBase.KEY_UPSYNCINDEX} INTEGER,${ColumnsBase.KEY_OWNERUSERID} TEXT)";
            db.execute(createTableActivityapproval);

            String createTableActivityapprovaltype = "CREATE TABLE IF NOT EXISTS ${TablesBase.TABLE_ACTIVITYAPPROVALTYPE}(${ColumnsBase.KEY_ID} INTEGER PRIMARY KEY AUTOINCREMENT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_ACTIVITYAPPROVALTYPEID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_ACTIVITYAPPROVALTYPECODE} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_ACTIVITYAPPROVALTYPENAME} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_DESCRIPTION} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_ACTIVITYTYPEID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_CREATEDON} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_CREATEDBY} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_MODIFIEDON} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_MODIFIEDBY} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_ISACTIVE} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_UID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_APPUSERID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_APPUSERGROUPID} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_ISARCHIVED} TEXT,${ColumnsBase.KEY_ACTIVITYAPPROVALTYPE_ISDELETED} TEXT,${ColumnsBase.KEY_ISDIRTY} TEXT,${ColumnsBase.KEY_ISACTIVE} TEXT,${ColumnsBase.KEY_ISDELETED} TEXT,${ColumnsBase.KEY_UPSYNCMESSAGE} TEXT,${ColumnsBase.KEY_DOWNSYNCMESSAGE} TEXT,${ColumnsBase.KEY_SCREATEDON} TEXT,${ColumnsBase.KEY_SMODIFIEDON} TEXT,${ColumnsBase.KEY_CREATEDBYUSER} TEXT,${ColumnsBase.KEY_MODIFIEDBYUSER} TEXT,${ColumnsBase.KEY_UPSYNCINDEX} INTEGER,${ColumnsBase.KEY_OWNERUSERID} TEXT)";
            db.execute(createTableActivityapprovaltype);

            String createTableCompetitor = "CREATE TABLE IF NOT EXISTS ${TablesBase.TABLE_COMPETITOR}(${ColumnsBase.KEY_ID} INTEGER PRIMARY KEY AUTOINCREMENT,${ColumnsBase.KEY_COMPETITOR_COMPETITORID} TEXT,${ColumnsBase.KEY_COMPETITOR_COMPETITORCODE} TEXT,${ColumnsBase.KEY_COMPETITOR_COMPETITORNAME} TEXT,${ColumnsBase.KEY_COMPETITOR_DESCRIPTION} TEXT,${ColumnsBase.KEY_COMPETITOR_CREATEDON} TEXT,${ColumnsBase.KEY_COMPETITOR_CREATEDBY} TEXT,${ColumnsBase.KEY_COMPETITOR_MODIFIEDON} TEXT,${ColumnsBase.KEY_COMPETITOR_MODIFIEDBY} TEXT,${ColumnsBase.KEY_COMPETITOR_ISACTIVE} TEXT,${ColumnsBase.KEY_COMPETITOR_UID} TEXT,${ColumnsBase.KEY_COMPETITOR_APPUSERID} TEXT,${ColumnsBase.KEY_COMPETITOR_APPUSERGROUPID} TEXT,${ColumnsBase.KEY_COMPETITOR_ISARCHIVED} TEXT,${ColumnsBase.KEY_COMPETITOR_ISDELETED} TEXT,${ColumnsBase.KEY_ISDIRTY} TEXT,${ColumnsBase.KEY_ISACTIVE} TEXT,${ColumnsBase.KEY_ISDELETED} TEXT,${ColumnsBase.KEY_UPSYNCMESSAGE} TEXT,${ColumnsBase.KEY_DOWNSYNCMESSAGE} TEXT,${ColumnsBase.KEY_SCREATEDON} TEXT,${ColumnsBase.KEY_SMODIFIEDON} TEXT,${ColumnsBase.KEY_CREATEDBYUSER} TEXT,${ColumnsBase.KEY_MODIFIEDBYUSER} TEXT,${ColumnsBase.KEY_UPSYNCINDEX} INTEGER,${ColumnsBase.KEY_OWNERUSERID} TEXT)";
            db.execute(createTableCompetitor);

            String createTableFinancialinstitution = "CREATE TABLE IF NOT EXISTS ${TablesBase.TABLE_FINANCIALINSTITUTION}(${ColumnsBase.KEY_ID} INTEGER PRIMARY KEY AUTOINCREMENT,${ColumnsBase.KEY_FINANCIALINSTITUTION_FINANCIALINSTITUTIONID} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_FINANCIALINSTITUTIONCODE} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_FINANCIALINSTITUTIONNAME} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_DESCRIPTION} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_CREATEDON} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_CREATEDBY} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_MODIFIEDON} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_MODIFIEDBY} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_ISACTIVE} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_UID} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_APPUSERID} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_APPUSERGROUPID} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_ISARCHIVED} TEXT,${ColumnsBase.KEY_FINANCIALINSTITUTION_ISDELETED} TEXT,${ColumnsBase.KEY_ISDIRTY} TEXT,${ColumnsBase.KEY_ISACTIVE} TEXT,${ColumnsBase.KEY_ISDELETED} TEXT,${ColumnsBase.KEY_UPSYNCMESSAGE} TEXT,${ColumnsBase.KEY_DOWNSYNCMESSAGE} TEXT,${ColumnsBase.KEY_SCREATEDON} TEXT,${ColumnsBase.KEY_SMODIFIEDON} TEXT,${ColumnsBase.KEY_CREATEDBYUSER} TEXT,${ColumnsBase.KEY_MODIFIEDBYUSER} TEXT,${ColumnsBase.KEY_UPSYNCINDEX} INTEGER,${ColumnsBase.KEY_OWNERUSERID} TEXT)";
            db.execute(createTableFinancialinstitution);

            String createTableOpportunityapproval = "CREATE TABLE IF NOT EXISTS ${TablesBase.TABLE_OPPORTUNITYAPPROVAL}(${ColumnsBase.KEY_ID} INTEGER PRIMARY KEY AUTOINCREMENT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_OPPORTUNITYAPPROVALID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_OPPORTUNITYAPPROVALCODE} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_OPPORTUNITYAPPROVALTITLE} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_OPPORTUNITYAPPROVALTYPEID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_OPPORTUNITYID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_REQUESTDATE} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_REQUESTDETAIL} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_ISSUBMITTED} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_PARENTOPPORTUNITYAPPROVALID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_APPROVALSTATUS} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_APPROVALBYAPPUSERID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_APPROVALTIME} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_APPROVERREMARKS} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_CREATEDBY} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_CREATEDON} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_MODIFIEDBY} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_MODIFIEDON} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_DEVICEIDENTIFIER} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_REFERENCEIDENTIFIER} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_LOCATION} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_ISACTIVE} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_UID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_APPUSERID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_APPUSERGROUPID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_ISARCHIVED} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVAL_ISDELETED} TEXT,${ColumnsBase.KEY_ISDIRTY} TEXT,${ColumnsBase.KEY_ISACTIVE} TEXT,${ColumnsBase.KEY_ISDELETED} TEXT,${ColumnsBase.KEY_UPSYNCMESSAGE} TEXT,${ColumnsBase.KEY_DOWNSYNCMESSAGE} TEXT,${ColumnsBase.KEY_SCREATEDON} TEXT,${ColumnsBase.KEY_SMODIFIEDON} TEXT,${ColumnsBase.KEY_CREATEDBYUSER} TEXT,${ColumnsBase.KEY_MODIFIEDBYUSER} TEXT,${ColumnsBase.KEY_UPSYNCINDEX} INTEGER,${ColumnsBase.KEY_OWNERUSERID} TEXT)";
            db.execute(createTableOpportunityapproval);

            String createTableOpportunityapprovaltype = "CREATE TABLE IF NOT EXISTS ${TablesBase.TABLE_OPPORTUNITYAPPROVALTYPE}(${ColumnsBase.KEY_ID} INTEGER PRIMARY KEY AUTOINCREMENT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_OPPORTUNITYAPPROVALTYPEID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_OPPORTUNITYAPPROVALTYPECODE} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_OPPORTUNITYAPPROVALTYPENAME} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_DESCRIPTION} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_OPPORTUNITYTYPEID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_CREATEDON} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_CREATEDBY} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_MODIFIEDON} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_MODIFIEDBY} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_ISACTIVE} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_UID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_APPUSERID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_APPUSERGROUPID} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_ISARCHIVED} TEXT,${ColumnsBase.KEY_OPPORTUNITYAPPROVALTYPE_ISDELETED} TEXT,${ColumnsBase.KEY_ISDIRTY} TEXT,${ColumnsBase.KEY_ISACTIVE} TEXT,${ColumnsBase.KEY_ISDELETED} TEXT,${ColumnsBase.KEY_UPSYNCMESSAGE} TEXT,${ColumnsBase.KEY_DOWNSYNCMESSAGE} TEXT,${ColumnsBase.KEY_SCREATEDON} TEXT,${ColumnsBase.KEY_SMODIFIEDON} TEXT,${ColumnsBase.KEY_CREATEDBYUSER} TEXT,${ColumnsBase.KEY_MODIFIEDBYUSER} TEXT,${ColumnsBase.KEY_UPSYNCINDEX} INTEGER,${ColumnsBase.KEY_OWNERUSERID} TEXT)";
            db.execute(createTableOpportunityapprovaltype);

            if (!await ColumnsExists(db,TablesBase.TABLE_ACCOUNT, ColumnsBase.KEY_ACCOUNT_ASSIGNEDBYAPPUSERID)) {
                String alterTableAccountAddKeyAssignedbyappuserid = "ALTER TABLE ${TablesBase.TABLE_ACCOUNT} ADD ${ColumnsBase.KEY_ACCOUNT_ASSIGNEDBYAPPUSERID} TEXT";
                db.execute(alterTableAccountAddKeyAssignedbyappuserid);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_CONTACT, ColumnsBase.KEY_CONTACT_ASSIGNEDBYAPPUSERID)) {
                String alterTableContactAddKeyAssignedbyappuserid = "ALTER TABLE ${TablesBase.TABLE_CONTACT} ADD ${ColumnsBase.KEY_CONTACT_ASSIGNEDBYAPPUSERID} TEXT";
                db.execute(alterTableContactAddKeyAssignedbyappuserid);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_ACTIVITY, ColumnsBase.KEY_ACTIVITY_ISAPPROVALREQUIRED)) {
                String alterTableActivityAddKeyIsapprovalrequired = "ALTER TABLE ${TablesBase.TABLE_ACTIVITY} ADD ${ColumnsBase.KEY_ACTIVITY_ISAPPROVALREQUIRED} TEXT";
                db.execute(alterTableActivityAddKeyIsapprovalrequired);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_OPPORTUNITY, ColumnsBase.KEY_OPPORTUNITY_LOSTTOCOMPETITOR)) {
                String alterTableOpportunityAddKeyLosttocompetitor = "ALTER TABLE ${TablesBase.TABLE_OPPORTUNITY} ADD ${ColumnsBase.KEY_OPPORTUNITY_LOSTTOCOMPETITOR} TEXT";
                db.execute(alterTableOpportunityAddKeyLosttocompetitor);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_OPPORTUNITY, ColumnsBase.KEY_OPPORTUNITY_REASONFOROPPORTUNITYSTATUS)) {
                String alterTableOpportunityAddKeyReasonforopportunitystatus = "ALTER TABLE ${TablesBase.TABLE_OPPORTUNITY} ADD ${ColumnsBase.KEY_OPPORTUNITY_REASONFOROPPORTUNITYSTATUS} TEXT";
                db.execute(alterTableOpportunityAddKeyReasonforopportunitystatus);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_OPPORTUNITY, ColumnsBase.KEY_OPPORTUNITY_OPPORTUNITYIDENTIFIER)) {
                String alterTableOpportunityAddKeyOpportunityidentifier = "ALTER TABLE ${TablesBase.TABLE_OPPORTUNITY} ADD ${ColumnsBase.KEY_OPPORTUNITY_OPPORTUNITYIDENTIFIER} TEXT";
                db.execute(alterTableOpportunityAddKeyOpportunityidentifier);
            }


            if (!await ColumnsExists(db,TablesBase.TABLE_OPPORTUNITY, ColumnsBase.KEY_OPPORTUNITY_PURCHASEORDERNUMBER)) {
                String alterTableOpportunityAddKeyPurchaseordernumber = "ALTER TABLE ${TablesBase.TABLE_OPPORTUNITY} ADD ${ColumnsBase.KEY_OPPORTUNITY_PURCHASEORDERNUMBER} TEXT";
                db.execute(alterTableOpportunityAddKeyPurchaseordernumber);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_OPPORTUNITY, ColumnsBase.KEY_OPPORTUNITY_QUOTATIONNUMBER)) {
                String alterTableOpportunityAddKeyQuotationnumber = "ALTER TABLE ${TablesBase.TABLE_OPPORTUNITY} ADD ${ColumnsBase.KEY_OPPORTUNITY_QUOTATIONNUMBER} TEXT";
                db.execute(alterTableOpportunityAddKeyQuotationnumber);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_OPPORTUNITY, ColumnsBase.KEY_OPPORTUNITY_ISFINANCEREQUIRED)) {
                String alterTableOpportunityAddKeyIsfinancerequired = "ALTER TABLE ${TablesBase.TABLE_OPPORTUNITY} ADD ${ColumnsBase.KEY_OPPORTUNITY_ISFINANCEREQUIRED} TEXT";
                db.execute(alterTableOpportunityAddKeyIsfinancerequired);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_OPPORTUNITY, ColumnsBase.KEY_OPPORTUNITY_FINANCEBY)) {
                String alterTableOpportunityAddKeyFinanceby = "ALTER TABLE ${TablesBase.TABLE_OPPORTUNITY} ADD ${ColumnsBase.KEY_OPPORTUNITY_FINANCEBY} TEXT";
                db.execute(alterTableOpportunityAddKeyFinanceby);
            }

            if (!await ColumnsExists(db,TablesBase.TABLE_OPPORTUNITY, ColumnsBase.KEY_OPPORTUNITY_FINANCEREMARKS)) {
                String alterTableOpportunityAddKeyFinanceremarks = "ALTER TABLE ${TablesBase.TABLE_OPPORTUNITY} ADD ${ColumnsBase.KEY_OPPORTUNITY_FINANCEREMARKS} TEXT";
                db.execute(alterTableOpportunityAddKeyFinanceremarks);
            }



        } catch (Exception ex) {
        }
    }