import 'package:happsales_crm/database/Handlers/OpportunityHandlers/OpportunityFulfillmentStatusDataHandlerBase.dart';

class OpportunityFulfillmentStatusDataHandler extends OpportunityFulfillmentStatusDataHandlerBase{
  
}