
class Account {
  int id;
  String accountID;
  String accountCode;
  String accountName;
  String accountLocation;
  String accountIdentifier;
  String accountSegmentID;
  String accountStatusID;
  String accountTypeID;
  String parentAccountID;
  String industryName;
  String website;
  String turnover;
  String numberOfEmployees;
  String creditRatingID;
  String currencyID;
  String primaryContactName;
  String phone;
  String email;
  String fax;
  String addressLine1;
  String addressLine2;
  String addressLine3;
  String city;
  String state;
  String country;
  String pin;
  String territoryName;
  String gpsCoordinates;
  String logoImagePath;
  String logoImageContent;
  String localMediaPath;
  String isUploaded;
  String taxPayerIdentificationNumber;
  String freeTextField1;
  String freeTextField2;
  String freeTextField3;
  String tags;
  String marketingContactID;
  String createdBy;
  String createdOn;
  String modifiedBy;
  String modifiedOn;
  String deviceIdentifier;
  String referenceIdentifier;
  String isActive;
  String uid;
  String appUserID;
  String appUserGroupID;
  String isArchived;
  String isDeleted;
  String leadQualificationID;
  String isDirty;
  String isActive1;
  String isDeleted1;
  String upSyncMessage;
  String downSyncMessage;
  String sCreatedOn;
  String sModifiedOn;
  String createdByUser;
  String modifiedByUser;
  int upSyncIndex;
  String ownerUserID;

  Account({
    required this.id,
    required this.accountID,
    required this.accountCode,
    required this.accountName,
    required this.accountLocation,
    required this.accountIdentifier,
    required this.accountSegmentID,
    required this.accountStatusID,
    required this.accountTypeID,
    required this.parentAccountID,
    required this.industryName,
    required this.website,
    required this.turnover,
    required this.numberOfEmployees,
    required this.creditRatingID,
    required this.currencyID,
    required this.primaryContactName,
    required this.phone,
    required this.email,
    required this.fax,
    required this.addressLine1,
    required this.addressLine2,
    required this.addressLine3,
    required this.city,
    required this.state,
    required this.country,
    required this.pin,
    required this.territoryName,
    required this.gpsCoordinates,
    required this.logoImagePath,
    required this.logoImageContent,
    required this.localMediaPath,
    required this.isUploaded,
    required this.taxPayerIdentificationNumber,
    required this.freeTextField1,
    required this.freeTextField2,
    required this.freeTextField3,
    required this.tags,
    required this.marketingContactID,
    required this.createdBy,
    required this.createdOn,
    required this.modifiedBy,
    required this.modifiedOn,
    required this.deviceIdentifier,
    required this.referenceIdentifier,
    required this.isActive,
    required this.uid,
    required this.appUserID,
    required this.appUserGroupID,
    required this.isArchived,
    required this.isDeleted,
    required this.leadQualificationID,
    required this.isDirty,
    required this.isActive1,
    required this.isDeleted1,
    required this.upSyncMessage,
    required this.downSyncMessage,
    required this.sCreatedOn,
    required this.sModifiedOn,
    required this.createdByUser,
    required this.modifiedByUser,
    required this.upSyncIndex,
    required this.ownerUserID,
  });

   factory Account.fromJson(Map<String, dynamic> json) {
    return Account(
      id: json['Id'],
      accountID: json['AccountID'],
      accountCode: json['AccountCode'],
      accountName: json['AccountName'],
      accountLocation: json['AccountLocation'],
      accountIdentifier: json['AccountIdentifier'],
      accountSegmentID: json['AccountSegmentID'],
      accountStatusID: json['AccountStatusID'],
      accountTypeID: json['AccountTypeID'],
      parentAccountID: json['ParentAccountID'],
      industryName: json['IndustryName'],
      website: json['Website'],
      turnover: json['Turnover'],
      numberOfEmployees: json['NumberOfEmployees'],
      creditRatingID: json['CreditRatingID'],
      currencyID: json['CurrencyID'],
      primaryContactName: json['PrimaryContactName'],
      phone: json['Phone'],
      email: json['Email'],
      fax: json['Fax'],
      addressLine1: json['AddressLine1'],
      addressLine2: json['AddressLine2'],
      addressLine3: json['AddressLine3'],
      city: json['City'],
      state: json['State'],
      country: json['Country'],
      pin: json['PIN'],
      territoryName: json['TerritoryName'],
      gpsCoordinates: json['GPSCoordinates'],
      logoImagePath: json['LogoImagePath'],
      logoImageContent: json['LogoImageContent'],
      localMediaPath: json['LocalMediaPath'],
      isUploaded: json['IsUploaded'],
      taxPayerIdentificationNumber: json['TaxPayerIdentificationNumber'],
      freeTextField1: json['FreeTextField1'],
      freeTextField2: json['FreeTextField2'],
      freeTextField3: json['FreeTextField3'],
      tags: json['Tags'],
      marketingContactID: json['MarketingContactID'],
      createdBy: json['CreatedBy'],
      createdOn: json['CreatedOn'],
      modifiedBy: json['ModifiedBy'],
      modifiedOn: json['ModifiedOn'],
      deviceIdentifier: json['DeviceIdentifier'],
      referenceIdentifier: json['ReferenceIdentifier'],
      isActive: json['IsActive'],
      uid: json['Uid'],
      appUserID: json['AppUserID'],
      appUserGroupID: json['AppUserGroupID'],
      isArchived: json['IsArchived'],
      isDeleted: json['IsDeleted'],
      leadQualificationID: json['LeadQualificationID'],
      isDirty: json['IsDirty'],
      isActive1: json['IsActive1'],
      isDeleted1: json['IsDeleted1'],
      upSyncMessage: json['UpSyncMessage'],
      downSyncMessage: json['DownSyncMessage'],
      sCreatedOn: json['SCreatedOn'],
      sModifiedOn: json['SModifiedOn'],
      createdByUser: json['CreatedByUser'],
      modifiedByUser: json['ModifiedByUser'],
      upSyncIndex: json['UpSyncIndex'],
      ownerUserID: json['OwnerUserID'],
    );
  }

  //make to json for all of the above
  Map<String, dynamic> toJson() {
    return {
      'Id': id,
      'AccountID': accountID,
      'AccountCode': accountCode,
      'AccountName': accountName,
      'AccountLocation': accountLocation,
      'AccountIdentifier': accountIdentifier,
      'AccountSegmentID': accountSegmentID,
      'AccountStatusID': accountStatusID,
      'AccountTypeID': accountTypeID,
      'ParentAccountID': parentAccountID,
      'IndustryName': industryName,
      'Website': website,
      'Turnover': turnover,
      'NumberOfEmployees': numberOfEmployees,
      'CreditRatingID': creditRatingID,
      'CurrencyID': currencyID,
      'PrimaryContactName': primaryContactName,
      'Phone': phone,
      'Email': email,
      'Fax': fax,
      'AddressLine1': addressLine1,
      'AddressLine2': addressLine2,
      'AddressLine3': addressLine3,
      'City': city,
      'State': state,
      'Country': country,
      'PIN': pin,
      'TerritoryName': territoryName,
      'GPSCoordinates': gpsCoordinates,
      'LogoImagePath': logoImagePath,
      'LogoImageContent': logoImageContent,
      'LocalMediaPath': localMediaPath,
      'IsUploaded': isUploaded,
      'TaxPayerIdentificationNumber': taxPayerIdentificationNumber,
      'FreeTextField1': freeTextField1,
      'FreeTextField2': freeTextField2,
      'FreeTextField3': freeTextField3,
      'Tags': tags,
      'MarketingContactID': marketingContactID,
      'CreatedBy': createdBy,
      'CreatedOn': createdOn,
      'ModifiedBy': modifiedBy,
      'ModifiedOn': modifiedOn,
      'DeviceIdentifier': deviceIdentifier,
      'ReferenceIdentifier': referenceIdentifier,
      'IsActive': isActive,
      'Uid': uid,
      'AppUserID': appUserID,
      'AppUserGroupID': appUserGroupID,
      'IsArchived': isArchived,
      'IsDeleted': isDeleted,
      'LeadQualificationID': leadQualificationID,
      'IsDirty': isDirty,
      'IsActive1': isActive1,
      'IsDeleted1': isDeleted1,
      'UpSyncMessage': upSyncMessage,
      'DownSyncMessage': downSyncMessage,
      'SCreatedOn': sCreatedOn,
      'SModifiedOn': sModifiedOn,
      'CreatedByUser': createdByUser,
      'ModifiedByUser': modifiedByUser,
      'UpSyncIndex': upSyncIndex,
      'OwnerUserID': ownerUserID,



    };
  }


}
// Define a factory method to create
