import '../../Models/BaseEntity.dart';

class ActivityBase  extends BaseEntity{
  String? _activityID;
  String? _activityCode;
  String? _activityTitle;
  String? _activityTypeID;
  String? _leadSource;
  String? _accountID;
  String? _contactID;
  String? _opportunityID;
  String? _activityMeasure;
  String? _activityDate;
  String? _activityEndDate;
  String? _assignmentDetails;
  String? _activityDetails;
  String? _activityPriorityID;
  String? _totalAmount;
  String? _amountCollected;
  String? _currencyID;
  String? _collectionDetails;
  String? _isTravelled;
  String? _travelPurposeName;
  String? _activityStatusID;
  String? _needFollowUpActivity;
  String? _parentActivityID;
  String? _activityAssignmentID;
  String? _expectedCompletionDate;
  String? _productInstallationDetailID;
  String? _invoiceID;
  String? _workflowProgressID;
  String? _tags;
  String? _remarks;
  String? _freeTextField1;
  String? _freeTextField2;
  String? _freeTextField3;
  String? _isApprovalRequired;
  String? _isApproved;
  String? _marketingContactID;
  String? _workflowStageID;
  String? _isWorkflowStageUpdated;
  String? _leadQualificationID;
  String? _createdBy;
  String? _createdOn;
  String? _modifiedBy;
  String? _modifiedOn;
  String? _deviceIdentifier;
  String? _referenceIdentifier;
  String? _location;
  String? _isActive;
  String? _isLocked;
  String? _uid;
  String? _appUserID;
  String? _appUserGroupID;
  String? _isArchived;
  String? _isDeleted;
  String? _successAlertMessage;
  String? _failureAlertMessage;
  String? _approvalStatus;
  String? _approvalDetails;
  String? _activityTypeName;
  String? _accountName;
  String? _contactName;
  String? _opportunityName;
  String? _activityPriorityName;
  String? _currencyName;
  String? _activityStatusName;
  String? _parentActivityTitle;
  String? _activityAssignmentTitle;
  String? _productInstallationDetailCode;
  String? _invoiceTitle;
  String? _workflowProgressName;
  String? _companyName;
  String? _workFlowStageName;
  String? _leadQualificationTitle;
  String? _appUserName;
  String? _appUserGroupName;
  String? _isApprovalRequiredOnCompletion;
  String? _completedDate;
   String? _principalName;
     String ?_activityCodeInternal; 

     // Setters and getters for these two
      String? get activityCodeInternal => _activityCodeInternal;
  set activityCodeInternal(String? value) {

    _activityCodeInternal = value;
  }
  String? get principalName => _principalName;

  set principalName(String? value) {
    _principalName = value;
  }


  // Getters
  String? get activityID => _activityID;
  String? get activityCode => _activityCode;
  String? get activityTitle => _activityTitle;
  String? get activityTypeID => _activityTypeID;
  String? get leadSource => _leadSource;
  String? get accountID => _accountID;
  String? get contactID => _contactID;
  String? get opportunityID => _opportunityID;
  String? get activityMeasure => _activityMeasure;
  String? get activityDate => _activityDate;
  String? get activityEndDate => _activityEndDate;
  String? get assignmentDetails => _assignmentDetails;
  String? get activityDetails => _activityDetails;
  String? get activityPriorityID => _activityPriorityID;
  String? get totalAmount => _totalAmount;
  String? get amountCollected => _amountCollected;
  String? get currencyID => _currencyID;
  String? get collectionDetails => _collectionDetails;
  String? get isTravelled => _isTravelled;
  String? get travelPurposeName => _travelPurposeName;
  String? get activityStatusID => _activityStatusID;
  String? get needFollowUpActivity => _needFollowUpActivity;
  String? get parentActivityID => _parentActivityID;
  String? get activityAssignmentID => _activityAssignmentID;
  String? get expectedCompletionDate => _expectedCompletionDate;
  String? get productInstallationDetailID => _productInstallationDetailID;
  String? get invoiceID => _invoiceID;
  String? get workflowProgressID => _workflowProgressID;
  String? get tags => _tags;
  String? get remarks => _remarks;
  String? get freeTextField1 => _freeTextField1;
  String? get freeTextField2 => _freeTextField2;
  String? get freeTextField3 => _freeTextField3;
  String? get isApprovalRequired => _isApprovalRequired;
  String? get isApproved => _isApproved;
  String? get marketingContactID => _marketingContactID;
  String? get workflowStageID => _workflowStageID;
  String? get isWorkflowStageUpdated => _isWorkflowStageUpdated;
  String? get leadQualificationID => _leadQualificationID;
  String? get createdBy => _createdBy;
  String? get createdOn => _createdOn;
  String? get modifiedBy => _modifiedBy;
  String? get modifiedOn => _modifiedOn;
  String? get deviceIdentifier => _deviceIdentifier;
  String? get referenceIdentifier => _referenceIdentifier;
  String? get location => _location;
  String? get isActive => _isActive;
  String? get isLocked => _isLocked;
  String? get uid => _uid;
  String? get appUserID => _appUserID;
  String? get appUserGroupID => _appUserGroupID;
  String? get isArchived => _isArchived;
  String? get isDeleted => _isDeleted;
  String? get successAlertMessage => _successAlertMessage;
  String? get failureAlertMessage => _failureAlertMessage;
  String? get approvalStatus => _approvalStatus;
  String? get approvalDetails => _approvalDetails;
  String? get activityTypeName => _activityTypeName;
  String? get accountName => _accountName;
  String? get contactName => _contactName;
  String? get opportunityName => _opportunityName;
  String? get activityPriorityName => _activityPriorityName;
  String? get currencyName => _currencyName;
  String? get activityStatusName => _activityStatusName;
  String? get parentActivityTitle => _parentActivityTitle;
  String? get activityAssignmentTitle => _activityAssignmentTitle;
  String? get productInstallationDetailCode => _productInstallationDetailCode;
  String? get invoiceTitle => _invoiceTitle;
  String? get workflowProgressName => _workflowProgressName;
  String? get companyName => _companyName;
  String? get workFlowStageName => _workFlowStageName;
  String? get leadQualificationTitle => _leadQualificationTitle;
  String? get appUserName => _appUserName;
  String? get appUserGroupName => _appUserGroupName;
  String? get isApprovalRequiredOnCompletion => _isApprovalRequiredOnCompletion;
  String? get completedDate => _completedDate;

  // Setters
  set activityID(String? value) => _activityID = value;
  set activityCode(String? value) => _activityCode = value;
  set activityTitle(String? value) => _activityTitle = value;
  set activityTypeID(String? value) => _activityTypeID = value;
  set leadSource(String? value) => _leadSource = value;
  set accountID(String? value) => _accountID = value;
  set contactID(String? value) => _contactID = value;
  set opportunityID(String? value) => _opportunityID = value;
  set activityMeasure(String? value) => _activityMeasure = value;
  set activityDate(String? value) => _activityDate = value;
  set activityEndDate(String? value) => _activityEndDate = value;
  set assignmentDetails(String? value) => _assignmentDetails = value;
  set activityDetails(String? value) => _activityDetails = value;
  set activityPriorityID(String? value) => _activityPriorityID = value;
  set totalAmount(String? value) => _totalAmount = value;
  set amountCollected(String? value) => _amountCollected = value;
  set currencyID(String? value) => _currencyID = value;
  set collectionDetails(String? value) => _collectionDetails = value;
  set isTravelled(String? value) => _isTravelled = value;
  set travelPurposeName(String? value) => _travelPurposeName = value;
  set activityStatusID(String? value) => _activityStatusID = value;
  set needFollowUpActivity(String? value) => _needFollowUpActivity = value;
  set parentActivityID(String? value) => _parentActivityID = value;
  set activityAssignmentID(String? value) => _activityAssignmentID = value;
  set expectedCompletionDate(String? value) => _expectedCompletionDate = value;
  set productInstallationDetailID(String? value) => _productInstallationDetailID = value;
  set invoiceID(String? value) => _invoiceID = value;
  set workflowProgressID(String? value) => _workflowProgressID = value;
  set tags(String? value) => _tags = value;
  set remarks(String? value) => _remarks = value;
  set freeTextField1(String? value) => _freeTextField1 = value;
  set freeTextField2(String? value) => _freeTextField2 = value;
  set freeTextField3(String? value) => _freeTextField3 = value;
  set isApprovalRequired(String? value) => _isApprovalRequired = value;
  set isApproved(String? value) => _isApproved = value;
  set marketingContactID(String? value) => _marketingContactID = value;
  set workflowStageID(String? value) => _workflowStageID = value;
  set isWorkflowStageUpdated(String? value) => _isWorkflowStageUpdated = value;
  set leadQualificationID(String? value) => _leadQualificationID = value;
  set createdBy(String? value) => _createdBy = value;
  set createdOn(String? value) => _createdOn = value;
  set modifiedBy(String? value) => _modifiedBy = value;
  set modifiedOn(String? value) => _modifiedOn = value;
  set deviceIdentifier(String? value) => _deviceIdentifier = value;
  set referenceIdentifier(String? value) => _referenceIdentifier = value;
  set location(String? value) => _location = value;
  set isActive(String? value) => _isActive = value;
  set isLocked(String? value) => _isLocked = value;
  set uid(String? value) => _uid = value;
  set appUserID(String? value) => _appUserID = value;
  set appUserGroupID(String? value) => _appUserGroupID = value;
  set isArchived(String? value) => _isArchived = value;
  set isDeleted(String? value) => _isDeleted = value;
  set successAlertMessage(String? value) => _successAlertMessage = value;
  set failureAlertMessage(String? value) => _failureAlertMessage = value;
  set approvalStatus(String? value) => _approvalStatus = value;
  set approvalDetails(String? value) => _approvalDetails = value;
  set activityTypeName(String? value) => _activityTypeName = value;
  set accountName(String? value) => _accountName = value;
  set contactName(String? value) => _contactName = value;
  set opportunityName(String? value) => _opportunityName = value;
  set activityPriorityName(String? value) => _activityPriorityName = value;
  set currencyName(String? value) => _currencyName = value;
  set activityStatusName(String? value) => _activityStatusName = value;
  set parentActivityTitle(String? value) => _parentActivityTitle = value;
  set activityAssignmentTitle(String? value) => _activityAssignmentTitle = value;
  set productInstallationDetailCode(String? value) => _productInstallationDetailCode = value;
  set invoiceTitle(String? value) => _invoiceTitle = value;
  set workflowProgressName(String? value) => _workflowProgressName = value;
  set companyName(String? value) => _companyName = value;
  set workFlowStageName(String? value) => _workFlowStageName = value;
  set leadQualificationTitle(String? value) => _leadQualificationTitle = value;
  set appUserName(String? value) => _appUserName = value;
  set appUserGroupName(String? value) => _appUserGroupName = value;
  set isApprovalRequiredOnCompletion(String? value) => _isApprovalRequiredOnCompletion = value;
  set completedDate(String? value) => _completedDate = value;

  // Constructor
  ActivityBase();

Map<String, dynamic> toJson() {
  final Map<String, dynamic> data = new Map<String, dynamic>();
  data['ActivityID'] = _activityID;
  data['ActivityCode'] = _activityCode;
  data['ActivityTitle'] = _activityTitle;
  data['ActivityTypeID'] = _activityTypeID;
  data['LeadSource'] = _leadSource;
  data['AccountID'] = _accountID;
  data['ContactID'] = _contactID;
  data['OpportunityID'] = _opportunityID;
  data['ActivityMeasure'] = _activityMeasure;
  data['ActivityDate'] = _activityDate;
  data['ActivityEndDate'] = _activityEndDate;
  data['AssignmentDetails'] = _assignmentDetails;
  data['ActivityDetails'] = _activityDetails;
  data['ActivityPriorityID'] = _activityPriorityID;
  data['TotalAmount'] = _totalAmount;
  data['AmountCollected'] = _amountCollected;
  data['CurrencyID'] = _currencyID;
  data['CollectionDetails'] = _collectionDetails;
  data['IsTravelled'] = _isTravelled;
  data['TravelPurposeName'] = _travelPurposeName;
  data['ActivityStatusID'] = _activityStatusID;
  data['NeedFollowUpActivity'] = _needFollowUpActivity;
  data['ParentActivityID'] = _parentActivityID;
  data['ActivityAssignmentID'] = _activityAssignmentID;
  data['ExpectedCompletionDate'] = _expectedCompletionDate;
  data['ProductInstallationDetailID'] = _productInstallationDetailID;
  data['InvoiceID'] = _invoiceID;
  data['WorkflowProgressID'] = _workflowProgressID;
  data['Tags'] = _tags;
  data['Remarks'] = _remarks;
  data['FreeTextField1'] = _freeTextField1;
  data['FreeTextField2'] = _freeTextField2;
  data['FreeTextField3'] = _freeTextField3;
  data['IsApprovalRequired'] = _isApprovalRequired;
  data['IsApproved'] = _isApproved;
  data['MarketingContactID'] = _marketingContactID;
  data['WorkflowStageID'] = _workflowStageID;
  data['IsWorkflowStageUpdated'] = _isWorkflowStageUpdated;
  data['LeadQualificationID'] = _leadQualificationID;
  data['CreatedBy'] = _createdBy;
  data['CreatedOn'] = _createdOn;
  data['ModifiedBy'] = _modifiedBy;
  data['ModifiedOn'] = _modifiedOn;
  data['DeviceIdentifier'] = _deviceIdentifier;
  data['ReferenceIdentifier'] = _referenceIdentifier;
  data['Location'] = _location;
  data['IsActive'] = _isActive;
  data['IsLocked'] = _isLocked;
  data['UID'] = _uid;
  data['AppUserID'] = _appUserID;
  data['AppUserGroupID'] = _appUserGroupID;
  data['IsArchived'] = _isArchived;
  data['IsDeleted'] = _isDeleted;
  data['SuccessAlertMessage'] = _successAlertMessage;
  data['FailureAlertMessage'] = _failureAlertMessage;
  data['ApprovalStatus'] = _approvalStatus;
  data['ApprovalDetails'] = _approvalDetails;
  data['ActivityTypeName'] = _activityTypeName;
  data['AccountName'] = _accountName;
  data['ContactName'] = _contactName;
  data['OpportunityName'] = _opportunityName;
  data['ActivityPriorityName'] = _activityPriorityName;
  data['CurrencyName'] = _currencyName;
  data['ActivityStatusName'] = _activityStatusName;
  data['ParentActivityTitle'] = _parentActivityTitle;
  data['ActivityAssignmentTitle'] = _activityAssignmentTitle;
  data['ProductInstallationDetailCode'] = _productInstallationDetailCode;
  data['InvoiceTitle'] = _invoiceTitle;
  data['WorkflowProgressName'] = _workflowProgressName;
  data['CompanyName'] = _companyName;
  data['WorkFlowStageName'] = _workFlowStageName;
  data['LeadQualificationTitle'] = _leadQualificationTitle;
  data['AppUserName'] = _appUserName;
  data['AppUserGroupName'] = _appUserGroupName;
  data['IsApprovalRequiredOnCompletion'] = _isApprovalRequiredOnCompletion;
  data['CompletedDate'] = _completedDate;

  //for new

  //  String? _principalName;
  //    String ?_activityCodeInternal; 

  data['PrincipalName'] = _principalName;

  data['ActivityCodeInternal'] = _activityCodeInternal;




  return data;
}
ActivityBase.fromMapObject(Map<String, dynamic> map) {
  _activityID = map['ActivityID'];
  _activityCode = map['ActivityCode'];
  _activityTitle = map['ActivityTitle'];
  _activityTypeID = map['ActivityTypeID'];
  _leadSource = map['LeadSource'];
  _accountID = map['AccountID'];
  _contactID = map['ContactID'];
  _opportunityID = map['OpportunityID'];
  _activityMeasure = map['ActivityMeasure'];
  _activityDate = map['ActivityDate'];
  _activityEndDate = map['ActivityEndDate'];
  _assignmentDetails = map['AssignmentDetails'];
  _activityDetails = map['ActivityDetails'];
  _activityPriorityID = map['ActivityPriorityID'];
  _totalAmount = map['TotalAmount'];
  _amountCollected = map['AmountCollected'];
  _currencyID = map['CurrencyID'];
  _collectionDetails = map['CollectionDetails'];
  _isTravelled = map['IsTravelled'];
  _travelPurposeName = map['TravelPurposeName'];
  _activityStatusID = map['ActivityStatusID'];
  _needFollowUpActivity = map['NeedFollowUpActivity'];
  _parentActivityID = map['ParentActivityID'];
  _activityAssignmentID = map['ActivityAssignmentID'];
  _expectedCompletionDate = map['ExpectedCompletionDate'];
  _productInstallationDetailID = map['ProductInstallationDetailID'];
  _invoiceID = map['InvoiceID'];
  _workflowProgressID = map['WorkflowProgressID'];
  _tags = map['Tags'];
  _remarks = map['Remarks'];
  _freeTextField1 = map['FreeTextField1'];
  _freeTextField2 = map['FreeTextField2'];
  _freeTextField3 = map['FreeTextField3'];
  _isApprovalRequired = map['IsApprovalRequired'];
  _isApproved = map['IsApproved'];
  _marketingContactID = map['MarketingContactID'];
  _workflowStageID = map['WorkflowStageID'];
  _isWorkflowStageUpdated = map['IsWorkflowStageUpdated'];
  _leadQualificationID = map['LeadQualificationID'];
  _createdBy = map['CreatedBy'];
  _createdOn = map['CreatedOn'];
  _modifiedBy = map['ModifiedBy'];
  _modifiedOn = map['ModifiedOn'];
  _deviceIdentifier = map['DeviceIdentifier'];
  _referenceIdentifier = map['ReferenceIdentifier'];
  _location = map['Location'];
  _isActive = map['IsActive'];
  _isLocked = map['IsLocked'];
  _uid = map['UID'];
  _appUserID = map['AppUserID'];
  _appUserGroupID = map['AppUserGroupID'];
  _isArchived = map['IsArchived'];
  _isDeleted = map['IsDeleted'];
  _successAlertMessage = map['SuccessAlertMessage'];
  _failureAlertMessage = map['FailureAlertMessage'];
  _approvalStatus = map['ApprovalStatus'];
  _approvalDetails = map['ApprovalDetails'];
  _activityTypeName = map['ActivityTypeName'];
  _accountName = map['AccountName'];
  _contactName = map['ContactName'];
  _opportunityName = map['OpportunityName'];
  _activityPriorityName = map['ActivityPriorityName'];
  _currencyName = map['CurrencyName'];
  _activityStatusName = map['ActivityStatusName'];
  _parentActivityTitle = map['ParentActivityTitle'];
  _activityAssignmentTitle = map['ActivityAssignmentTitle'];
  _productInstallationDetailCode = map['ProductInstallationDetailCode'];
  _invoiceTitle = map['InvoiceTitle'];
  _workflowProgressName = map['WorkflowProgressName'];
  _companyName = map['CompanyName'];
  _workFlowStageName = map['WorkFlowStageName'];
  _leadQualificationTitle = map['LeadQualificationTitle'];
  _appUserName = map['AppUserName'];
  _appUserGroupName = map['AppUserGroupName'];
  _isApprovalRequiredOnCompletion = map['IsApprovalRequiredOnCompletion'];
  _completedDate = map['CompletedDate'];

  //  String? _principalName;
  //    String ?_activityCodeInternal; 

  _principalName = map['PrincipalName'];

  _activityCodeInternal = map['ActivityCodeInternal'];

}



  }